name: dormlink
description: "Find your perfect study buddy and co-habitant with this vibrant app, connecting KFUPM students to compatible roommates through intelligent matching, direct chat, and seamless university portal integration."
publish_to: "none"
version: 1.0.4

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.2
  shared_preferences: ^2.0.0
  uuid: ^4.0.0
  url_launcher: ^6.0.0
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
